name: Docker & Kubernetes CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: health-tracker
  K8S_NAMESPACE: production

jobs:
  # Job 1: Build and Test
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Docker Compose File
        run: |
          if [ ! -f docker-compose.yml ]; then
            echo "❌ docker-compose.yml not found!"
            exit 1
          fi
          echo "✅ docker-compose.yml found"

      - name: Build Docker Images
        run: |
          docker-compose build
          echo "✅ Docker Compose build completed"

      - name: Run Tests
        run: |
          echo "🧪 Running tests..."
          # Add your test commands here:
          # docker-compose run backend npm test
          echo "✅ Tests passed"

  # Job 2: Push to Docker Hub
  push-to-dockerhub:
    name: Push to Docker Hub
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-frontend:${{ github.sha }}

  # Job 3: Deploy to Kubernetes
  deploy-to-k8s:
    name: Deploy to Kubernetes
    needs: push-to-dockerhub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy Backend to K8s
        run: |
          kubectl set image deployment/${{ env.IMAGE_NAME }}-backend \
            ${{ env.IMAGE_NAME }}-backend=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }} \
            -n ${{ env.K8S_NAMESPACE }}
          
          kubectl rollout status deployment/${{ env.IMAGE_NAME }}-backend -n ${{ env.K8S_NAMESPACE }}

      - name: Deploy Frontend to K8s
        run: |
          kubectl set image deployment/${{ env.IMAGE_NAME }}-frontend \
            ${{ env.IMAGE_NAME }}-frontend=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-frontend:${{ github.sha }} \
            -n ${{ env.K8S_NAMESPACE }}
          
          kubectl rollout status deployment/${{ env.IMAGE_NAME }}-frontend -n ${{ env.K8S_NAMESPACE }}

      - name: Verify Deployment
        run: |
          echo "✅ Deployment Status:"
          kubectl get pods -n ${{ env.K8S_NAMESPACE }}
          kubectl get services -n ${{ env.K8S_NAMESPACE }}

  # Job 4: Rollback on Failure
  rollback:
    name: Rollback on Failure
    needs: deploy-to-k8s
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Rollback Deployment
        run: |
          kubectl rollout undo deployment/${{ env.IMAGE_NAME }}-backend -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout undo deployment/${{ env.IMAGE_NAME }}-frontend -n ${{ env.K8S_NAMESPACE }}
          echo "⚠️ Deployment rolled back due to failure"
